name: "Deploy para VPS"
on: 
  push:
    branches:
      - main
jobs:
  build_deploy:
    runs-on: ubuntu-latest
    environment: main

    steps:
      - name: "Baixar o código" 
        uses: actions/checkout@v5

      - name: "Copiar arquivos para VPS"
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.HOST }}
          username: "root"
          password: ${{ secrets.PASSWORD }}
          source: "."
          target: "/var/www/www.camposvasconcelos.com.br"

      - name: "Build da aplicação"
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.HOST }}
          username: "root"
          password: ${{ secrets.PASSWORD }}
          script: |
            cd /var/www/www.camposvasconcelos.com.br
            npm install
            chown -R www-data:www-data .
            cd frontend
            npm run build
            
        
