name: "Deploy para VPS"
on: 
  push:
    branches:
      - main
jobs:
  build_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: "Baixar o código" 
        uses: actions/checkout@v4

      - name: "Copiar arquivos para VPS"
        uses: appleboy/scp-action@v0.1.7
        with:
          host: "147.93.12.242"
          username: "root"
          password: ${{ secrets.PASSWORD }}
          source: "."
          target: "/var/www/www.camposvasconcelos.com.br"

      - name: "Build da aplicação"
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: "147.93.12.242"
          username: "root"
          password: ${{ secrets.PASSWORD }}
          script: |
            cd /var/www/www.camposvasconcelos.com.br
            npm install
            chown -R www-data:www-data .
            cd /frontend
            npm run build
            
        
